import { supabase, useMock } from '../config/supabase.js';

class RequestService {
    /**
     * Fetches all dropdown data needed for the Request Form
     */
    async getMetadata() {
        if (useMock || !supabase) {
            return {
                municipalities: [
                    { id: 'm1', name: 'Sibutad' },
                    { id: 'm2', name: 'Dapitan' },
                    { id: 'm3', name: 'Dipolog' },
                ],
                barangays: [
                    { id: 'b1', name: 'Pob. Sibutad', municipality_id: 'm1' },
                    { id: 'b2', name: 'Calamba', municipality_id: 'm1' },
                ],
                docTypes: [
                    { id: 'dt1', name: 'Certified True Copy of Latest Tax Declaration', prefix: 'TD' },
                    { id: 'dt2', name: 'Certified True Copy of Old Tax Declaration', prefix: 'CTC' },
                    { id: 'dt3', name: 'Certificate of Landholding', prefix: 'CLH' },
                ],
                purposes: [
                    { id: 'p1', label: 'For Settling of Tax Obligation', code: 'TAX_OBLIGATION' },
                    { id: 'p2', label: 'For Court and Other Legal Purposes', code: 'LEGAL' },
                    { id: 'p3', label: 'Others', code: 'OTHERS' },
                ],
                classifications: [
                    { id: 'c1', label: 'Agricultural', code: 'AGRICULTURAL' },
                    { id: 'c2', label: 'Residential', code: 'RESIDENTIAL' },
                    { id: 'c3', label: 'Commercial', code: 'COMMERCIAL' },
                    { id: 'c4', label: 'Industrial', code: 'INDUSTRIAL' },
                    { id: 'c5', label: 'Special', code: 'SPECIAL' },
                ],
                propertyTypes: [
                    { id: 'pt1', label: 'Land', code: 'LAND' },
                    { id: 'pt2', label: 'Building', code: 'BUILDING' },
                    { id: 'pt3', label: 'Machinery', code: 'MACHINERY' },
                    { id: 'pt4', label: 'Others', code: 'OTHERS' },
                ],
            };
        }

        const { data: municipalities } = await supabase.from('municipalities').select('id, name');
        const { data: barangays } = await supabase.from('barangays').select('id, name, municipality_id');
        const { data: docTypes } = await supabase.from('document_types').select('id, name, prefix');

        // Fetch categories and values separately to safely group them
        const { data: categories } = await supabase.from('lookup_categories').select('id, code');
        const { data: values } = await supabase
            .from('lookup_values')
            .select('id, category_id, code, label')
            .eq('is_active', true);

        const categoryMap = {};
        categories?.forEach((c) => {
            categoryMap[c.id] = c.code;
        });

        const purposes = [];
        const classifications = [];
        const propertyTypes = [];

        values?.forEach((v) => {
            const catCode = categoryMap[v.category_id];
            if (catCode === 'PURPOSE') {
                purposes.push({ id: v.id, label: v.label, code: v.code });
            } else if (catCode === 'CLASSIFICATION') {
                classifications.push({ id: v.id, label: v.label, code: v.code });
            } else if (catCode === 'PROPERTY_TYPE') {
                propertyTypes.push({ id: v.id, label: v.label, code: v.code });
            }
        });

        return { municipalities, barangays, docTypes, purposes, classifications, propertyTypes };
    }

    /**
     * Saves a new request and its associated document types
     */
    async saveNewRequest(formData, authUserId) {
        // 1. Get the UUID of the staff from our staff table
        const { data: staff } = await supabase
            .from('staff')
            .select('id')
            .eq('auth_user_id', authUserId)
            .single();

        if (!staff) throw new Error("Staff profile not found.");

        // 2. Insert into 'requests' table
        // Note: control_number ('REQ-...') is generated by your SQL trigger
        const { data: request, error: reqError } = await supabase
            .from('requests')
            .insert([{
                declarant_name: formData.declarantName,
                request_date: formData.requestDate,
                requested_by_name: formData.requestedByName,
                authorization_required: formData.authRequired,
                purpose_id: formData.purposeId,
                action_taken: formData.actionTaken || 'PENDING',
                encoded_by: staff.id,
                status: 'DRAFT'
            }])
            .select()
            .single();

        if (reqError) throw reqError;

        // 3. Link document types in 'request_documents'
        // Note: document_number ('TD-...') is generated by your SQL trigger
        const docLinks = formData.documentTypeIds.map(docId => ({
            request_id: request.id,
            document_type_id: docId
        }));

        const { error: docError } = await supabase.from('request_documents').insert(docLinks);
        if (docError) throw docError;

        return request;
    }

    /**
     * Updates an existing request and its document types
     */
    async updateRequest(id, formData) {
        if (useMock || !supabase) {
            return { id, ...formData };
        }

        // 1. Update requests table
        const updateData = {
            declarant_name: formData.declarantName,
            request_date: formData.requestDate,
            requested_by_name: formData.requestedByName,
            authorization_required: formData.authRequired,
            purpose_id: formData.purposeId || null,
            action_taken: formData.actionTaken || 'PENDING',
        };

        if (formData.status) {
            updateData.status = formData.status;
        }

        const { data: request, error: reqError } = await supabase
            .from('requests')
            .update(updateData)
            .eq('id', id)
            .select()
            .single();

        if (reqError) throw reqError;

        // 2. Update document types in request_documents
        if (formData.documentTypeIds) {
            // Remove existing links
            await supabase.from('request_documents').delete().eq('request_id', id);

            // Link new document types
            const docLinks = formData.documentTypeIds.map(docId => ({
                request_id: id,
                document_type_id: docId
            }));

            const { error: docError } = await supabase.from('request_documents').insert(docLinks);
            if (docError) throw docError;
        }

        return request;
    }

    /**
     * Deletes a request and all its database dependencies
     */
    async deleteRequest(id) {
        if (useMock || !supabase) {
            return;
        }

        // 1. Get all encoded_tax_declarations associated with the request
        const { data: etds } = await supabase
            .from('encoded_tax_declarations')
            .select('id')
            .eq('request_id', id);

        if (etds && etds.length > 0) {
            const etdIds = etds.map(e => e.id);
            // Delete property types
            await supabase.from('encoded_property_types').delete().in('encoded_tax_declaration_id', etdIds);
            // Delete assessment rows
            await supabase.from('encoded_assessment_rows').delete().in('encoded_tax_declaration_id', etdIds);
            // Delete the tax declarations
            await supabase.from('encoded_tax_declarations').delete().eq('request_id', id);
        }

        // 2. Get all request_documents associated with the request
        const { data: reqDocs } = await supabase
            .from('request_documents')
            .select('id')
            .eq('request_id', id);

        if (reqDocs && reqDocs.length > 0) {
            const docIds = reqDocs.map(d => d.id);
            // Delete generated documents
            await supabase.from('generated_documents').delete().in('request_document_id', docIds);
            // Delete request documents
            await supabase.from('request_documents').delete().eq('request_id', id);
        }

        // 3. Delete request
        const { error } = await supabase.from('requests').delete().eq('id', id);
        if (error) throw error;
    }

    /**
     * Fetches all requests
     */
    async getAllRequests() {
        if (useMock || !supabase) {
            // return some mock requests
            return [
                {
                    id: 'r1',
                    control_number: 'REF-2026-0001',
                    declarant_name: 'Juan Dela Cruz',
                    request_date: '2026-07-14',
                    requested_by_name: 'Juan Dela Cruz',
                    authorization_required: false,
                    purpose_id: 'p1',
                    action_taken: 'APPROVED',
                    status: 'DRAFT',
                    documentTypeIds: ['dt1'],
                    property_location: 'Pob. Sibutad, Sibutad',
                },
                {
                    id: 'r2',
                    control_number: 'REF-2026-0002',
                    declarant_name: 'Maria Clara',
                    request_date: '2026-07-14',
                    requested_by_name: 'Ibarra',
                    authorization_required: true,
                    purpose_id: 'p2',
                    action_taken: 'PENDING',
                    status: 'DRAFT',
                    documentTypeIds: ['dt2', 'dt3'],
                    property_location: 'Calamba, Sibutad',
                }
            ];
        }

        const { data, error } = await supabase
            .from('requests')
            .select(`
                *,
                request_documents (
                    document_type_id
                )
            `)
            .order('created_at', { ascending: false });

        if (error) throw error;

        return data.map(req => ({
            ...req,
            documentTypeIds: req.request_documents ? req.request_documents.map(d => d.document_type_id) : []
        }));
    }
}

export default new RequestService();