import { supabase } from '../config/supabase.js';

class RequestService {
    /**
     * Fetches all dropdown data needed for the Request Form
     */
    async getMetadata() {
        const { data: municipalities } = await supabase.from('municipalities').select('id, name');
        const { data: barangays } = await supabase.from('barangays').select('id, name, municipality_id');
        const { data: docTypes } = await supabase.from('document_types').select('id, name, prefix');
        
        // Fetch purposes (Assuming category 'PURPOSE' exists in lookup_categories)
        const { data: purposes } = await supabase
            .from('lookup_values')
            .select('id, label')
            .eq('is_active', true);

        return { municipalities, barangays, docTypes, purposes };
    }

    /**
     * Saves a new request and its associated document types
     */
    async saveNewRequest(formData, authUserId) {
        // 1. Get the UUID of the staff from our staff table
        const { data: staff } = await supabase
            .from('staff')
            .select('id')
            .eq('auth_user_id', authUserId)
            .single();

        if (!staff) throw new Error("Staff profile not found.");

        // 2. Insert into 'requests' table
        // Note: control_number ('REQ-...') is generated by your SQL trigger
        const { data: request, error: reqError } = await supabase
            .from('requests')
            .insert([{
                declarant_name: formData.declarantName,
                request_date: formData.requestDate,
                requested_by_name: formData.requestedByName,
                authorization_required: formData.authRequired,
                purpose_id: formData.purposeId,
                action_taken: formData.actionTaken || 'PENDING',
                encoded_by: staff.id,
                status: 'DRAFT'
            }])
            .select()
            .single();

        if (reqError) throw reqError;

        // 3. Link document types in 'request_documents'
        // Note: document_number ('TD-...') is generated by your SQL trigger
        const docLinks = formData.documentTypeIds.map(docId => ({
            request_id: request.id,
            document_type_id: docId
        }));

        const { error: docError } = await supabase.from('request_documents').insert(docLinks);
        if (docError) throw docError;

        return request;
    }
}

export default new RequestService();