import type { ReactElement } from 'react';

/**
 * Shared helpers for document-type detection used by the Dashboard
 * (Recent Transactions), Reports & Analytics (Declarant Records) and the
 * Transaction Registry.
 *
 * Reference numbers are generated by the backend as `PREFIX-YEAR-RANDOM`
 * (e.g. NLH-2026-000123) where PREFIX comes from the document_types table:
 *   TD  → Tax Declaration
 *   NLH → No Land Holding
 *   LH  → Landholding
 *
 * When a transaction has no request_documents rows the registry API returns
 * an empty list, so the UI used to show "N/A". Falling back to the reference
 * prefix recovers the document type for those records without any backend
 * changes.
 */

const TaxDeclarationIcon = () => <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round"><line x1="3" y1="21" x2="21" y2="21"></line><line x1="6" y1="18" x2="6" y2="11"></line><line x1="10" y1="18" x2="10" y2="11"></line><line x1="14" y1="18" x2="14" y2="11"></line><line x1="18" y1="18" x2="18" y2="11"></line><polygon points="12 3 21 9 3 9"></polygon></svg>;
const LandholdingIcon = () => <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="8" y1="13" x2="16" y2="13" /><line x1="8" y1="17" x2="16" y2="17" /></svg>;
const NoLandholdingIcon = () => <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><path d="M9 15l2 2 4-4" /></svg>;
const GenericDocIcon = () => <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round"><path d="M7 3h8l4 4v14H7z" /></svg>;

export interface DocPillMeta {
    className: string;
    Icon: () => ReactElement;
}

/** Reference-number prefix → human-readable document type (display label). */
const REF_PREFIX_LABELS: Record<string, string> = {
    TD: 'Tax Declaration',
    NLH: 'No Land Holding',
    LH: 'Landholding',
};

/**
 * Recovers the document type from a reference number's prefix, or null
 * when the prefix isn't recognized. Case-insensitive.
 */
export function getDocumentTypeFromReference(referenceNumber?: string | null): string | null {
    if (!referenceNumber) return null;
    const prefix = referenceNumber.split('-')[0].toUpperCase();
    return REF_PREFIX_LABELS[prefix] ?? null;
}

/**
 * Returns the pill styling + icon for a document-type string. Matches both
 * the registry API spellings ("Certificate of Land Holding") and the
 * frontend union spellings ("Certificate of Landholding"), plus the short
 * display labels used when the type is recovered from a reference prefix.
 */
export function getDocPillMeta(documentType: string): DocPillMeta {
    switch (documentType) {
        case 'Certificate of No Landholding':
        case 'No Land Holding':
            return { className: 'tr-doc-pill--nlh', Icon: NoLandholdingIcon };
        case 'Certificate of Landholding':
        case 'Certificate of Land Holding':
        case 'Landholding':
            return { className: 'tr-doc-pill--lh', Icon: LandholdingIcon };
        case 'Tax Declaration':
            return { className: 'tr-doc-pill--td', Icon: TaxDeclarationIcon };
        default:
            return { className: '', Icon: GenericDocIcon };
    }
}
